services:
  main:
    build: ./app-api
    tty: true

  worker-green:
    build: ./app-worker
    environment:
      WEIGHT: 80
      GROUP_ID: "worker-green"

  # this could be an updated image
  worker-blue:
    build: ./app-worker
    environment:
      WEIGHT: 20
      GROUP_ID: "worker-blue"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
